src/com/report/model/ReportService.java
package com.report.model;

import java.util.List;

public class ReportService {
	
	
	private Report_interface dao;

	public ReportService() {		
		dao = new ReportDAO();
	}
	
	public List<ReportVO> getAll(){
		return dao.getAll();
	}
	
	
}

src/com/report/model/ReportVO.java
package com.report.model;

public class ReportVO {
	
	private	Integer REPORT_NO; 
	private 	String REPORT; 
	private 	String REPORT_MSG; 
	private 	String REPORT_STATUS; 
	private 	String MANAGER_NO; 
	
	@Override
	public String toString() {
		return "ReportVO [REPORT_NO=" + REPORT_NO + ", REPORT=" + REPORT + ", REPORT_MSG=" + REPORT_MSG
				+ ", REPORT_STATUS=" + REPORT_STATUS + ", MANAGER_NO=" + MANAGER_NO + "]";
	}
	public Integer getREPORT_NO() {
		return REPORT_NO;
	}
	public void setREPORT_NO(Integer rEPORT_NO) {
		this.REPORT_NO = rEPORT_NO;
	}
	public String getREPORT() {
		return REPORT;
	}
	public void setREPORT(String rEPORT) {
		this.REPORT = rEPORT;
	}
	public String getREPORT_MSG() {
		return REPORT_MSG;
	}
	public void setREPORT_MSG(String rEPORT_MSG) {
		this.REPORT_MSG = rEPORT_MSG;
	}
	public String getREPORT_STATUS() {
		return REPORT_STATUS;
	}
	public void setREPORT_STATUS(String rEPORT_STATUS) {
		this.REPORT_STATUS = rEPORT_STATUS;
	}
	public String getMANAGER_NO() {
		return MANAGER_NO;
	}
	public void setMANAGER_NO(String mANAGER_NO) {
		this.MANAGER_NO = mANAGER_NO;
	}
	
	
	
}

src/com/report/model/Report_interface.java
package com.report.model;

import java.util.List;

public interface Report_interface {
	
	public void insert(ReportVO reportVO);
	public void update(ReportVO reportVO);
	public void delete(Integer REPORT_NO);
	public ReportVO findPrimaryKey(Integer REPORT_NO);
	public List<ReportVO> getAll();
	
}

WebContent/backstage/chat.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/backstage/css/basic.css" />
<link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet"/>
<title>基本版面</title>
</head>
<body>
	<div class="block1"></div>
	<div class="bg"><img src="<%=request.getContextPath()%>/backstage/img\bg.png" alt=""></div>
	<div class="main">
		<div class="main-div">
			<div class="panel-div">
				<!-- 姓名圖片 -->
				<div class="name">
					<img src="./img/tony.jfif" alt="" />
					<p>金城武</p>
				</div>

				<!-- 功能版面 -->

				<!-- 首頁公告 -->
				<div class="homepage">
					<a href="">
						<img src="./img/house.svg" alt="">
						<p>首頁公告</p>
					</a>
				</div>

				<!-- 人員管理 -->
				<div class="worker_management">
					<a href="">
						<img src="./img/member.svg" alt="">
						<p>人員管理</p>
					</a>
				</div>
				<!-- 管理員列表 -->
				<div class="worker_management_list none">
					<a href="">
						<p>管理員列表</p>
					</a>
				</div>

				<!-- 檢舉列表 -->
				<div class="report_list">
					<a href="">
						<img src="./img/list.svg" alt="">
						<p>檢舉列表</p>
					</a>
				</div>
				<!-- 檢舉清單  待審核名單 -->
				<div class="report_list_all none">
					<a href="">
						<p>檢舉清單</p>
					</a>
					<a href="">
						<p>待審核名單</p>
					</a>
				</div>
				<!-- 活動管理 -->
				<div class="event_management">
					<a href="">
						<img src="./img/events.svg" alt="">
						<p>活動管理</p>
					</a>
				</div>

				<!-- 會員管理 -->
				<div class="member_management">
					<a href="">
						<img src="./img/people.svg" alt="">
						<p>會員管理</p>
					</a>
				</div>
			</div>

			<!-- 內容板塊 -->
			<div class="panel-text">




				<jsp:include page="chat1.jsp">
					<jsp:param name="a" value="1" />
					<jsp:param name="b" value="2" />
				</jsp:include>





			</div>
		</div>
	</div>
	<div class="block"></div>
</body>
</html>

WebContent/backstage/chat1.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="<%=request.getContextPath()%>/backstage/css/friendchat.css" type="text/css" />
<style type="text/css">

</style>
<title>最大私人聊天室</title>
</head>
<body onload="connect();" onunload="disconnect();">
	<h3 id="statusOutput" class="statusOutput"></h3>
	<div id="row"></div>
	<div id="messagesArea" class="panel message-area" ></div>
	<div class="panel input-area">
		<input id="message" class="text-field" type="text" placeholder="Message" onkeydown="if (event.keyCode == 13) sendMessage();" /> 
		<input type="submit" id="sendMessage" class="button" value="Send" onclick="sendMessage();" /> 
		<input type="button" id="connect" class="button" value="Connect" onclick="connect();" /> 
		<input type="button" id="disconnect" class="button" value="Disconnect" onclick="disconnect();" />
	</div>
</body>
<script>
	var MyPoint = "/FriendWS/${userName}";
	var host = window.location.host;
	console.log(host);
	var path = window.location.pathname;
	console.log(path);
	var webCtx = path.substring(0, path.indexOf('/', 1));
	console.log(webCtx)
	var endPointURL = "ws://" + window.location.host + webCtx + MyPoint;
	console.log(endPointURL)

	var statusOutput = document.getElementById("statusOutput");
	var messagesArea = document.getElementById("messagesArea");
	var self = '${userName}';
	var webSocket;

	function connect() {
		// create a websocket
		webSocket = new WebSocket(endPointURL);

		webSocket.onopen = function(event) {
			console.log("Connect Success!");
			document.getElementById('sendMessage').disabled = false;
			document.getElementById('connect').disabled = true;
			document.getElementById('disconnect').disabled = false;
		};

		webSocket.onmessage = function(event) {
			var jsonObj = JSON.parse(event.data);
			if ("open" === jsonObj.type) {
				refreshFriendList(jsonObj);
			} else if ("history" === jsonObj.type) {
				messagesArea.innerHTML = '';
				var ul = document.createElement('ul');
				ul.id = "area";
				messagesArea.appendChild(ul);
				// 這行的jsonObj.message是從redis撈出跟好友的歷史訊息，再parse成JSON格式處理
				var messages = JSON.parse(jsonObj.message);
				for (var i = 0; i < messages.length; i++) {
					var historyData = JSON.parse(messages[i]);
					var showMsg = historyData.message;
					var li = document.createElement('li');
					// 根據發送者是自己還是對方來給予不同的class名, 以達到訊息左右區分
					historyData.sender === self ? li.className += 'me' : li.className += 'friend';
					li.innerHTML = showMsg;
					ul.appendChild(li);
				}
				messagesArea.scrollTop = messagesArea.scrollHeight;
			} else if ("chat" === jsonObj.type) {
				var li = document.createElement('li');
				jsonObj.sender === self ? li.className += 'me' : li.className += 'friend';
				li.innerHTML = jsonObj.message;
				console.log(li);
				document.getElementById("area").appendChild(li);
				messagesArea.scrollTop = messagesArea.scrollHeight;
			} else if ("close" === jsonObj.type) {
				refreshFriendList(jsonObj);
			}
			
		};

		webSocket.onclose = function(event) {
			console.log("Disconnected!");
		};
	}
	
	function sendMessage() {
		var inputMessage = document.getElementById("message");
		var friend = statusOutput.textContent;
		var message = inputMessage.value.trim();

		if (message === "") {
			alert("Input a message");
			inputMessage.focus();
		} else if (friend === "") {
			alert("Choose a friend");
		} else {
			var jsonObj = {
				"type" : "chat",
				"sender" : self,
				"receiver" : friend,
				"message" : message
			};
			webSocket.send(JSON.stringify(jsonObj));
			inputMessage.value = "";
			inputMessage.focus();
		}
	}
	
	// 有好友上線或離線就更新列表
	function refreshFriendList(jsonObj) {
		var friends = jsonObj.users;
		var row = document.getElementById("row");
		row.innerHTML = '';
		for (var i = 0; i < friends.length; i++) {
			if (friends[i] === self) { continue; }
			row.innerHTML +='<div id=' + i + ' class="column" name="friendName" value=' + friends[i] + ' ><h2>' + friends[i] + '</h2></div>';
		}
		addListener();
	}
	// 註冊列表點擊事件並抓取好友名字以取得歷史訊息
	function addListener() {
		var container = document.getElementById("row");
		container.addEventListener("click", function(e) {
			var friend = e.srcElement.textContent;
			updateFriendName(friend);
			var jsonObj = {
					"type" : "history",
					"sender" : self,
					"receiver" : friend,
					"message" : ""
				};
			webSocket.send(JSON.stringify(jsonObj));
		});
	}
	
	function disconnect() {
		webSocket.close();
		document.getElementById('sendMessage').disabled = true;
		document.getElementById('connect').disabled = false;
		document.getElementById('disconnect').disabled = true;
	}
	
	function updateFriendName(name) {
		statusOutput.innerHTML = name;
	}
</script>
</html>

WebContent/backstage/event_management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<%@ page import="com.manager.model.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.text.*"%>
<%@ page import="java.util.stream.Collectors"%>
<%@ page import="com.activity.model.*"%>

<%
	//登入驗證
	if (session.getAttribute("manager") == null) {
		RequestDispatcher dispatcher = request.getRequestDispatcher("/backstage/login.jsp");
		dispatcher.forward(request, response);
	}
	//將所有活動抓出
	ActivityService activitySvc = new ActivityService();
	List<ActivityVO> list = activitySvc.getAll();
	//濾出審核中活動		
	List<ActivityVO> listA0 = list.stream().filter(e -> e.getStatus().equals("a0"))
			.collect(Collectors.toList());
	//濾出通過活動
	List<ActivityVO> listA1 = list.stream().filter(e -> e.getStatus().equals("a1"))
			.collect(Collectors.toList());
	//濾出未通過活動
	List<ActivityVO> listA2 = list.stream().filter(e -> e.getStatus().equals("a2"))
			.collect(Collectors.toList());
	//濾出編輯中活動
	List<ActivityVO> listA3 = list.stream().filter(e -> e.getStatus().equals("a3"))
			.collect(Collectors.toList());

	pageContext.setAttribute("listA0", listA0);
	pageContext.setAttribute("listA1", listA1);
	pageContext.setAttribute("listA2", listA2);
	pageContext.setAttribute("listA3", listA3);
%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<link
	href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap"
	rel="stylesheet">
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/backstage/css/basic.css" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/backstage/css/backendmanagercheack1.css">
<title>活動管理</title>


</head>
<body>
	<div class="block1"></div>
	<div class="bg">
		<img src="<%=request.getContextPath()%>/backstage/img\bg.png" alt="">
	</div>
	<div class="main">
		<div class="main-div">
			<div class="panel-div">
				<!-- 姓名圖片 -->
				<div class="name">
					<img src="<%=request.getContextPath()%>/PicReader" alt="" />
					<p>${manager.nickname}</p>
				</div>
				<!-- 功能版面 -->

				<!-- 首頁公告 -->
				<div class="homepage">
					<a href="<%=request.getContextPath()%>/backstage/homepage.jsp"><img
						src="<%=request.getContextPath()%>/backstage/img/house.svg" alt="">
						<p>首頁公告</p></a>
				</div>
				<!-- 人員管理 -->
				<div class="worker_management">
					<a
						href="<%=request.getContextPath()%>/backstage/worker_management.jsp"><img
						src="<%=request.getContextPath()%>/backstage/img/member.svg"
						alt="">
						<p>人員管理</p></a>
				</div>
				<!-- 管理員列表 -->
				<div class="worker_management_list none">
					<a href=""><p>管理員列表</p></a>
				</div>
				<!-- 檢舉列表 -->
				<div class="report_list">
					<a href="<%=request.getContextPath()%>/backstage/report.jsp"><img
						src="<%=request.getContextPath()%>/backstage/img/list.svg" alt="">
						<p>檢舉列表</p></a>
				</div>
				<!-- 檢舉清單  待審核名單 -->
				<div class="report_list_all none">
					<a href=""><p>檢舉清單</p></a> <a href=""><p>待審核名單</p></a>
				</div>
				<!-- 活動管理 -->
				<div class="event_management">
					<a
						href="<%=request.getContextPath()%>/backstage/event_management.jsp"><img
						src="<%=request.getContextPath()%>/backstage/img/events.svg">
						<p>活動管理</p></a>
				</div>

				<!-- 會員管理 -->
				<div class="member_management">
					<a href=""><img
						src="<%=request.getContextPath()%>/backstage/img/people.svg"
						alt="">
						<p>會員管理</p></a>
				</div>

				<div>
					<form action="<%=request.getContextPath()%>/Logout">
						<button type="submit" class="logout">登出</button>
					</form>
				</div>
			</div>

			<!-- 內容板塊 -->
			<div class="panel-text">
				<header class="header">
					<div class="h1">
						<p></p>
					</div>
					<div>
						<a href=""><img class="logo"
							src="<%=request.getContextPath()%>/backstage/img/APE3.svg" alt="" /></a>
					</div>
				</header>
				<div class="line"></div>

				<div class="body_content_data">
					<div class="container">
						<h2>活動管理</h2>
						<select>
							<option value="a0" selected>待審核</option>
							<option value="a1">通過</option>
							<option value="a2">未通過</option>
							<option value="a3">編輯中</option>
						</select>


						<div class="over">
							<ul class="responsive-table">
								<li class="table-header">
									<div class="header-1">活動名稱</div>
									<div class="header-2">活動日期</div>
									<div class="header-3">活動類型</div>
									<div class="header-4">活動簡介</div>
									<div class="header-5">活動示意</div>
									<div class="header-6">審核</div>
								</li>

								<jsp:useBean id="acttypeDAO" scope="page"
									class="com.activitytype.model.ActivitytypeJDBCDAO" />

								<c:forEach var="activityVO" items="${listA0}">
									<li class="table-row a0" id="a0">
										<div class="col col-1" data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2" data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3" data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>
										</div>
										<div class="col col-4" data-label="INTRODUCTION">${activityVO.introuction}</div>
										<div class="col col-5" data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6" data-label="STATUS">
											<span class="STATUS">待審核</span>
										</div>
										<form action="<%=request.getContextPath()%>/EventManagement"
											method="GET">
											<input type="hidden" name="activityNo"
												value="${activityVO.activityNo}">
										</form>
									</li>
								</c:forEach>



								<c:forEach var="activityVO" items="${listA1}">
									<li class="table-row a1" id="a1">
										<div class="col col-1 " data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2 " data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3 " data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>

										</div>
										<div class="col col-4 " data-label="INTRODUCTION">${activityVO.introuction}</div>
										<div class="col col-5 " data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6 " data-label="STATUS">
											<span class="STATUS">通過</span>
										</div>
									</li>
								</c:forEach>


								<c:forEach var="activityVO" items="${listA2}">
									<li class="table-row a2" id="a2">
										<div class="col col-1 " data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2 " data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3 " data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>
										</div>
										<div class="col col-4 " data-label="INTRODUCTION">${activityVO.introuction}</div>
										<div class="col col-5 " data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6 " data-label="STATUS">
											<span class="STATUS">未通過</span>
										</div>
									</li>
								</c:forEach>
								<c:forEach var="activityVO" items="${listA3}">
									<li class="table-row a3" id="a3">
										<div class="col col-1 " data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2 " data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3 " data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>


										</div>
										<div class="col col-4 " data-label="INTRODUCTION">${activityVO.introuction}</div>
										<div class="col col-5 " data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6 " data-label="STATUS">
											<span class="STATUS">編輯中</span>
										</div>
									</li>
								</c:forEach>

							</ul>
						</div>
						<!-- 每一筆活動列出來 -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="block"></div>

	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script
		src="<%=request.getContextPath()%>/backstage/js/events_management.js"></script>
</body>
</html>

WebContent/backstage/event_management1.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="com.manager.model.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.text.*"%>
<%@ page import="com.activity.model.*"%>
<%@ page import="java.util.stream.Collectors"%>
<%@ page import="java.lang.*"%>

<%
	if (session.getAttribute("manager") == null) {
		RequestDispatcher dispatcher = request.getRequestDispatcher("/backstage/login.jsp");
		dispatcher.forward(request, response);
	}
%>


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link
	href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap"
	rel="stylesheet" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/backstage/css/basic.css" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/backstage/css/backendmanagercheack2.css">
<title>活動管理</title>
</head>
<body>
	<div class="block1"></div>
	<div class="bg">
		<img src="<%=request.getContextPath()%>/backstage/img\bg.png" alt="">
	</div>
	<div class="main">
		<div class="main-div">
			<div class="panel-div">
				<!-- 姓名圖片 -->
				<div class="name">
					<img src="<%=request.getContextPath()%>/PicReader" alt="" />
					<p>${manager.nickname}</p>
				</div>

				<!-- 功能版面 -->
				<!-- 首頁公告 -->
				<div class="homepage">
					<a href="<%=request.getContextPath()%>/backstage/homepage.jsp">
						<img src="<%=request.getContextPath()%>/backstage/img/house.svg"
						alt="">
						<p>首頁公告</p>
					</a>
				</div>

				<!-- 人員管理 -->
				<div class="worker_management">
					<a
						href="<%=request.getContextPath()%>/backstage/worker_management.jsp">
						<img src="<%=request.getContextPath()%>/backstage/img/member.svg"
						alt="">
						<p>人員管理</p>
					</a>
				</div>
				<!-- 管理員列表 -->
				<div class="worker_management_list none">
					<a href="">
						<p>管理員列表</p>
					</a>
				</div>

				<!-- 檢舉列表 -->
				<div class="report_list">
					<a href="<%=request.getContextPath()%>/backstage/report.jsp"> <img
						src="<%=request.getContextPath()%>/backstage/img/list.svg" alt="">
						<p>檢舉列表</p>
					</a>
				</div>
				<!-- 檢舉清單  待審核名單 -->
				<div class="report_list_all none">
					<a href="">
						<p>檢舉清單</p>
					</a> <a href="">
						<p>待審核名單</p>
					</a>
				</div>
				<!-- 活動管理 -->
				<div class="event_management">
					<a
						href="<%=request.getContextPath()%>/backstage/event_management.jsp">
						<img src="<%=request.getContextPath()%>/backstage/img/events.svg"
						alt="">
						<p>活動管理</p>
					</a>
				</div>

				<!-- 會員管理 -->
				<div class="member_management">
					<a href=""> <img
						src="<%=request.getContextPath()%>/backstage/img/people.svg"
						alt="">
						<p>會員管理</p>
					</a>
				</div>
				<div>
					<form action="<%=request.getContextPath()%>/Logout">
						<button type="submit" class="logout">登出</button>
					</form>
				</div>
			</div>

			<!-- 內容板塊 -->
			<div class="panel-text">

				<div class="body_content_data">
					<div class="container">
						<h2>活動審核</h2>
						<table class="TB_COLLAPSE">

							<tr class="">
								<th>項目</th>
								<th>明細</th>
							</tr>
							<tr>
								<td>活動編號</td>
								<td>${activityVO.activityNo}</td>
							</tr>
							<tr>
								<td>活動名稱</td>
								<td>${activityVO.activityName}</td>
							</tr>
							<tr>
								<td>活動開始日期</td>
								<td>${activityVO.startDate}</td>
							</tr>
							<tr>
								<td>活動結束日期</td>
								<td>${activityVO.closeDate}</td>
							</tr>
							<tr>
								<td>活動天數</td>
								<td>${activityVO.dayCount}</td>
							</tr>
							<tr>
								<td>活動時間</td>
								<td>${activityVO.activityHours}</td>
							</tr>
							<tr>
								<td>攤位數量</td>
								<td>${activityVO.rentCount}</td>
							</tr>
							<tr>
								<td>建立時間</td>
								<td>${activityVO.createDate}</td>
							</tr>
							<tr>
								<td>活動地址</td>
								<td>${activityVO.address}</td>
							</tr>
							<tr>
								<td>出租價格</td>
								<td>${activityVO.price}</td>
							</tr>
							<tr>
								<td>活動簡介</td>
								<td>${activityVO.introuction}</td>
							</tr>
							<tr>
								<td>活動圖片</td>
								<td><img
									src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}">
								</td>
							</tr>
							<tr>
								<td>活動類型</td>
								<td>小農商品</td>
							</tr>

							<tr>
								<td>審核狀態</td>
								<td>待審核</td>
							</tr>

						</table>


						<form action="<%=request.getContextPath()%>/EventVerify"
							method="post">
							<button type="submit" class="button1" name="verify" value="pass">通過</button>
							<button type="submit" class="button1" name="verify" value="fail">未通過</button>
						</form>





					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="block"></div>
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</body>

</html>